name: bavaria_kg
description: Bavaria.kg Автосервис BMW
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.14.5
  provider: ^6.1.1
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.0.0
  audioplayers: ^5.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  cached_network_image: ^3.3.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logoF.png
    - assets/images/carbon_fiber.png
    - assets/images/carbon_back.png
    - assets/images/carbon_bra.png
    - assets/sounds/intro.mp3
    - assets/images/main_fon_grad.png
    - assets/images/t_bg_bg.png
    - assets/images/main_fon.png
    - assets/images/card_back_gb.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700