name: bavaria_kg
description: Bavaria.kg Автосервис BMW
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.14.5
  provider: ^6.1.1
  qr_flutter: ^4.0.0
  mobile_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logoF.png
    - assets/images/carbon_fiber.png
    - assets/images/carbon_back.png
    - assets/images/carbon_bra.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"