// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiGf7f-WVwStvTB43pb6wquAkYCzL_Uv4',
    appId: '1:744863490088:web:15414d00ba0b9f08fb151d',
    messagingSenderId: '744863490088',
    projectId: 'bavaria-kg',
    authDomain: 'bavaria-kg.firebaseapp.com',
    storageBucket: 'bavaria-kg.firebasestorage.app',
    measurementId: 'G-MVMPTSGDSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE0Tjj9x6iC1flYRgXvq7VJB7nYFKq39Q',
    appId: '1:744863490088:android:42f5df040b18ff80fb151d',
    messagingSenderId: '744863490088',
    projectId: 'bavaria-kg',
    storageBucket: 'bavaria-kg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmgrXs-FZYvWPbk4RaAEzsnsy66kAUKpU',
    appId: '1:744863490088:ios:b89dee5ccd1e9b8dfb151d',
    messagingSenderId: '744863490088',
    projectId: 'bavaria-kg',
    storageBucket: 'bavaria-kg.firebasestorage.app',
    iosBundleId: 'com.bavaria.bavaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmgrXs-FZYvWPbk4RaAEzsnsy66kAUKpU',
    appId: '1:744863490088:ios:b89dee5ccd1e9b8dfb151d',
    messagingSenderId: '744863490088',
    projectId: 'bavaria-kg',
    storageBucket: 'bavaria-kg.firebasestorage.app',
    iosBundleId: 'com.bavaria.bavaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiGf7f-WVwStvTB43pb6wquAkYCzL_Uv4',
    appId: '1:744863490088:web:166fa8a62de0d8d1fb151d',
    messagingSenderId: '744863490088',
    projectId: 'bavaria-kg',
    authDomain: 'bavaria-kg.firebaseapp.com',
    storageBucket: 'bavaria-kg.firebasestorage.app',
    measurementId: 'G-KSDXPMYNRV',
  );
}
